### ISSUE TITLE
GIM / UGIM Labels?

### ISSUE THREAD

**Issue by chegg0** [CodePanter/Bluesky-OSRSLabeler#1]
I find it really funny how there's chunkman titles but there aren't titles for the official gamemodes of Group iron and unranked group iron!

**Comment by CodePanter** [comment]
Hello! Thank you for your suggestion! There is no rhyme or reason when it comes to the labels currently on offer; its just whatever came to mind or was suggested.
The 'group' gamemodes should definitely be added! 
Would you agree adding the following (without all the group size distinctions) would cover it?
- Group ironman
- Hardcore group ironman
- Unranked group ironman

**Comment by CodePanter** [comment]
These labels have now been added, so I'm closing this issue.
